# Generated by Django 4.0.10 on 2024-01-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogauthor')),
                ('ingredients', models.ManyToManyField(to='core.blogingredient')),
                ('instructions', models.ManyToManyField(to='core.bloginstruction')),
                ('notes', models.ManyToManyField(to='core.blognote')),
            ],
        ),
        migrations.AddField(
            model_name='blognote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
        ),
        migrations.AddField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
        ),
        migrations.AddField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
        ),
    ]
