# Generated by Django 4.0.10 on 2024-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogauthor_blogingredient_bloginstruction_blognote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='cook_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogrecipe',
            name='prep_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogrecipe',
            name='servings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogrecipe',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogrecipe',
            name='total_time',
            field=models.CharField(max_length=255),
        ),
    ]
