# Generated by Django 4.0.10 on 2024-01-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogrecipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
