# Generated by Django 4.0.10 on 2024-01-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blogrecipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='rating',
            field=models.FloatField(),
        ),
    ]
