# Generated by Django 4.0.10 on 2024-01-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blogrecipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
