# Generated by Django 4.0.10 on 2024-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blogrecipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
