# Generated by Django 4.0.10 on 2024-01-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blogrecipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='blogrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='blogrecipe',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
        ),
    ]
