# Generated by Django 4.0.10 on 2024-01-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_blogingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='blogrecipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.blogingredient'),
        ),
    ]
