# Generated by Django 4.0.10 on 2024-01-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_blogingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogingredient',
            name='recipe',
        ),
    ]
