# Generated by Django 4.0.10 on 2024-01-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blogingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogingredient',
            old_name='recipe',
            new_name='author',
        ),
    ]
