# Generated by Django 4.0.10 on 2024-01-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_recipe_blogingredient_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogingredient',
            name='author',
        ),
        migrations.AddField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.blogrecipe'),
            preserve_default=False,
        ),
    ]
