# Generated by Django 4.0.10 on 2024-01-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_blogingredient_author_blogingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='core.blogrecipe'),
        ),
        migrations.AlterField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='core.blogrecipe'),
        ),
        migrations.AlterField(
            model_name='blognote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.blogrecipe'),
        ),
    ]
