# Generated by Django 4.0.10 on 2024-01-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_blogingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.blogauthor'),
        ),
    ]
