# Generated by Django 4.0.10 on 2024-01-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_blogrecipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.blogrecipe'),
        ),
        migrations.AlterField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.blogrecipe'),
        ),
        migrations.AlterField(
            model_name='blognote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.blogrecipe'),
        ),
    ]
