# Generated by Django 4.0.10 on 2024-01-11 20:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.blog_recipe_image_file_path),
        ),
    ]
