# Generated by Django 4.0.10 on 2024-01-11 21:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_blogimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrecipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
