# Generated by Django 4.0.10 on 2024-01-11 21:33

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_blogrecipe_image_delete_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecipe',
            name='image',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.blog_recipe_image_file_path)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.blogrecipe')),
            ],
        ),
    ]
