# Generated by Django 4.0.10 on 2024-01-12 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_image_blogimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecipe',
            name='category',
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.blogauthor')),
            ],
        ),
        migrations.AddField(
            model_name='blogrecipe',
            name='category',
            field=models.ManyToManyField(to='core.blogcategory'),
        ),
    ]
