# Generated by Django 4.0.10 on 2024-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_blogrecipe_category_blogcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
