# Generated by Django 4.0.10 on 2024-01-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_blogrecipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecipe',
            name='category',
        ),
    ]
