# Generated by Django 4.0.10 on 2024-01-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_blogrecipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
