# Generated by Django 4.0.10 on 2024-01-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_blogrecipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
