# Generated by Django 4.0.10 on 2024-01-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_blogimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIngredientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lists', to='core.blogrecipe')),
            ],
        ),
        migrations.AlterField(
            model_name='blogingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.blogingredientlist'),
        ),
    ]
