# Generated by Django 4.0.10 on 2024-01-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_recipe_blogingredient_ingredient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.blogrecipe'),
        ),
    ]
