# Generated by Django 4.0.10 on 2024-01-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_blogingredientlist_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='core.blogrecipe'),
        ),
    ]
