# Generated by Django 4.0.10 on 2024-01-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_blogingredientlist_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInstructionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_list', to='core.blogrecipe')),
            ],
        ),
        migrations.AlterField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.bloginstructionlist'),
        ),
    ]
