# Generated by Django 4.0.10 on 2024-01-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_bloginstructionlist_alter_bloginstruction_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.blogrecipe'),
        ),
        migrations.DeleteModel(
            name='BlogInstructionList',
        ),
    ]
