# Generated by Django 4.0.10 on 2024-01-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_bloginstruction_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInstructionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_list', to='core.blogrecipe')),
            ],
        ),
    ]
