# Generated by Django 4.0.10 on 2024-01-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_bloginstructionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.bloginstructionlist'),
        ),
    ]
