# Generated by Django 4.0.10 on 2024-01-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_bloginstruction_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginstruction',
            old_name='recipe',
            new_name='instruction_list',
        ),
    ]
